# CMake script for embedding SQL code into a header file. This is done
# so that SQL commands are embedded into the application's executable, so no
# SQL commands are needed to be loaded from a file at runtime.

# Input variables:
#   - DBSQL_SCHEMA_SRC: Path to the SQL schema source file
#   - DBSQL_SRCS: List of SQL source files containing statements to embed
#   - DBSQL_OUTPUT_HPP: Path to the output C++ header file

cmake_minimum_required(VERSION 3.10)

set(DBSQL_OUTPUT_HPP_DIR "${CMAKE_CURRENT_BINARY_DIR}/embedded_sql")
set(DBSQL_OUTPUT_HPP "${DBSQL_OUTPUT_HPP_DIR}/EmbeddedSQLCode.hpp")

# Function to convert variable names from PascalCase or camelCase to UPPER_SNAKE_CASE
function(convert_to_upper_snake_case input_name output_variable)
    # Use the provided regex to find all words in the name
    string(REGEX MATCHALL "(([A-Z0-9]|(^[a-z]))[a-z0-9]+)|([A-Z]{2,})|[A-Z]" WORDS "${input_name}")

    # Join words with underscores and convert to uppercase
    set(result "")
    foreach(word ${WORDS})
        if(result)
            string(APPEND result "_${word}")
        else()
            set(result "${word}")
        endif()
    endforeach()

    # Convert to uppercase
    string(TOUPPER "${result}" result)

    set(${output_variable} "${result}" PARENT_SCOPE)
endfunction()

# Read and process the schema file
file(READ "${DBSQL_SCHEMA_SRC}" SCHEMA_CONTENT)

# Start building the header file
set(HEADER_CONTENT "")
string(APPEND HEADER_CONTENT "/*\n")
string(APPEND HEADER_CONTENT " * Note:\n")
string(APPEND HEADER_CONTENT " *\n")
string(APPEND HEADER_CONTENT " * This header file is MACHINE GENERATED!\n")
string(APPEND HEADER_CONTENT " * Do not edit this file because changes will be overwritten otherwise.\n")
string(APPEND HEADER_CONTENT " */\n\n")
string(APPEND HEADER_CONTENT "namespace ecim {\n")

# Embed the schema as a single entry
string(APPEND HEADER_CONTENT "    static const char* DBSQL_SCHEMA =\nR\"(")
string(APPEND HEADER_CONTENT "${SCHEMA_CONTENT}")
string(APPEND HEADER_CONTENT ")\";\n\n")

string(REPLACE " " ";" DBSQL_SRCS "${DBSQL_SRCS}")

# Process each SQL source file
foreach(SQL_FILE ${DBSQL_SRCS})
    file(READ "${SQL_FILE}" FILE_CONTENT)

    # Split content by semicolons to extract individual statements
    # and look for comments to identify statement names
    string(REGEX MATCHALL "--[A-Za-z]+[^;]*" STATEMENTS "${FILE_CONTENT}")

    foreach(STATEMENT ${STATEMENTS})
        # Extract the comment line (statement name in PascalCase)
        string(REGEX MATCH "\--[^\n]*" COMMENT "${STATEMENT}")
        string(REPLACE "\--" "" STATEMENT_NAME "${COMMENT}")
        string(STRIP "${STATEMENT_NAME}" STATEMENT_NAME)

        # Extract the SQL statement (everything after the comment)
        string(REGEX REPLACE "^--[^\n]*\n" "" SQL_STATEMENT "${STATEMENT}")
        string(STRIP "${SQL_STATEMENT}" SQL_STATEMENT)

        # Only add if we found a valid statement name and SQL
        if(STATEMENT_NAME AND SQL_STATEMENT)
            # Convert statement name to constant naming convention (DBSQL_<NAME>)
            convert_to_upper_snake_case(${STATEMENT_NAME} STATEMENT_NAME)
            set(CONST_NAME "DBSQL_${STATEMENT_NAME}")

            string(APPEND HEADER_CONTENT "    static const char *${CONST_NAME} =\nR\"(")
            string(APPEND HEADER_CONTENT "${SQL_STATEMENT}")
            string(APPEND HEADER_CONTENT ")\";\n\n")
        endif()
    endforeach()
endforeach()

string(APPEND HEADER_CONTENT "}\n")

# Write the header file
file(WRITE "${DBSQL_OUTPUT_HPP}" "${HEADER_CONTENT}")
message(STATUS "Generated embedded SQL header file: ${DBSQL_OUTPUT_HPP}")

target_include_directories(${PROJECT_NAME} PUBLIC ${DBSQL_OUTPUT_HPP_DIR})
