/*
 * Note:
 *
 * This header file is MACHINE GENERATED!
 * Do not edit this file because changes will be overwritten otherwise.
 */

namespace ecim {
    static const char* DBSQL_SCHEMA =
R"(-- ECIM Database Schema Version 1

BEGIN;

CREATE TABLE IF NOT EXISTS ElectronicComponents(
    ComponentID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL,
    Type INTEGER NOT NULL, --ElectronicComponent::Type enum
    Manufacturer TEXT NOT NULL,
    PartNumber TEXT,
    Description TEXT,
    Quantity NOT NULL DEFAULT 0,
    VoltageRating DOUBLE DEFAULT 0,
    CurrentRating DOUBLE DEFAULT 0,
    PowerRating DOUBLE DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Resistors(
    ResistorID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    Resistance DOUBLE DEFAULT 0, --Ohms
    ToleranceBand DOUBLE DEFAULT 0,
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

CREATE TABLE IF NOT EXISTS Capacitors(
    CapacitorID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    Type INTEGER NOT NULL, --Capacitor::Type enum
    Capacitance DOUBLE DEFAULT 0, --Farads
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

CREATE TABLE IF NOT EXISTS Inductors(
    InductorID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    Inductance DOUBLE DEFAULT 0, --Henrys
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

CREATE TABLE IF NOT EXISTS Diodes(
    DiodeID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    Type INTEGER NOT NULL,
    ForwardVoltage DOUBLE DEFAULT 0, --Volts
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

CREATE TABLE IF NOT EXISTS BJTransistors(
    TransistorID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    Gain DOUBLE DEFAULT 0, --hFE
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

CREATE TABLE IF NOT EXISTS FETransistors(
    TransistorID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    ThresholdVoltage DOUBLE DEFAULT 0, --Volts
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

CREATE TABLE IF NOT EXISTS Diodes(
    DiodeID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    Type INTEGER NOT NULL, --Diode::Type enum
    ForwardVoltage DOUBLE DEFAULT 0, --Volts
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

CREATE TABLE IF NOT EXISTS IntegratedCircuits(
    ChipID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    ComponentID INTEGER,
    PinCount INTEGER DEFAULT 0,
    Width DOUBLE DEFAULT 0, --milimeters
    Height DOUBLE DEFAULT 0, --milimeters
    Length DOUBLE DEFAULT 0, --milimeters
    FOREIGN KEY (ComponentID) REFERENCES ElectronicComponents(ComponentID)
);

COMMIT;
)";

    static const char *DBSQL_ADD_COMPONENT =
R"(INSERT INTO ElectronicComponents
(Name, Type, Manufacturer, PartNumber, Description, Quantity, VoltageRating,
CurrentRating, PowerRating)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?))";

    static const char *DBSQL_ADD_RESISTOR =
R"(INSERT INTO Resistors
(ComponentID, Resistance, ToleranceBand)
VALUES(?, ?, ?))";

    static const char *DBSQL_ADD_CAPACITOR =
R"(INSERT INTO Capacitors
(ComponentID, Type, Capacitance)
VALUES(?, ?, ?))";

    static const char *DBSQL_ADD_INDUCTOR =
R"(INSERT INTO Inductors
(ComponentID, Inductance)
VALUES(?, ?))";

    static const char *DBSQL_ADD_DIODE =
R"(INSERT INTO Diodes
(ComponentID, Type, ForwardVoltage)
VALUES(?, ?, ?))";

    static const char *DBSQL_ADD_BJ_TRANSISTOR =
R"(INSERT INTO BJTransistors
(ComponentID, Gain)
VALUES(?, ?))";

    static const char *DBSQL_ADD_FE_TRANSISTOR =
R"(INSERT INTO FETransistors
(ComponentID, ThresholdVoltage)
VALUES(?, ?))";

    static const char *DBSQL_ADD_INTEGRATED_CIRCUIT =
R"(INSERT INTO IntegratedCircuits
(ComponentID, PinCount, Width, Height, Length)
VALUES(?, ?, ?, ?, ?))";

}
